sudo: required

language: go

go:
  - 1.9.6

services:
  - redis-server
  - docker

jobs:
  include:
    - stage: test
      install:
        - docker run --name scylla -v $(pwd)/db.cql:/db/db.cql -p 9042:9042 -d scylladb/scylla
        - sleep 20
        - docker exec -it scylla cqlsh -f /db/db.cql
        - make deps
      script:
        - make test
    - stage: build
      if: branch IN (master, dockerhub, k8s_beta)
      install:
        # Overwrite install
        - echo "Start build"
      script:
        - make docker_build
        - docker images
        - make docker_run
        - docker ps -a
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make docker_push
