sudo: required

language: go

go:
  - 1.9.6

services:
  - redis-server
  - docker

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync -v
  - govendor add +e
  - govendor list

script:
  # runtest
  - go test -v -cover ./...
  # if test success, build image
  - docker build -t jneo8/pgurl-core .
  - docker run -d -p 8080:8080 jneo8/pgurl-core
  - docker ps -a

before_deploy:
  # Login dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # push to dockerhub
  - docker push jneo8/pgurl-core
